@startuml

hide empty members

class Client {
}

class Target {
  + Request()
}

class Adapter {
  + Request()
}

class Adaptee {
  + SpecificRequest()
}

class SpecificRequest {
}

Client --> Target
Target --|> Adapter
Adapter --|> Adaptee
Adapter --> SpecificRequest
@enduml